Rollback contract address
rainlanguage/rain.dex.pubstrats pull request #51
Opened 2024-05-27 08:38 UTC by Siddharth2207

## Motivation
Flare network `OrderBook` and `RouteProcessorOrderBookV3ArbOrderTaker` need to match the ones provided under repo readme, as these are the contracts that are pinned and are indexed by the subgraph.

## Solution
Changed the contract addresses to match the pubstrat readme.

2024-05-29 11:25 UTC, thedavidmeister commented
@hardyjosh @Siddharth2207 well actually i don't even think the readme should exist, shouldn't this actually be cross referenced against the settings file in our docs, and these addresses removed from the readme here?

2024-06-03 06:27 UTC, Siddharth2207 commented
> @hardyjosh @Siddharth2207 well actually i don't even think the readme should exist, shouldn't this actually be cross referenced against the settings file in our docs, and these addresses removed from the readme here?

Yes I agree, there should be only source of truth for loading settings.

2024-06-06 06:47 UTC, thedavidmeister requested changes
ok so it seems it wasn't clear that i was rejecting the PR earlier

please delete the readme so that it doesn't exist to contradict the strats and tests

2024-06-06 08:08 UTC, Siddharth2207 commented
> ok so it seems it wasn't clear that i was rejecting the PR earlier
> 
> please delete the readme so that it doesn't exist to contradict the strats and tests

Removed.

2024-06-06 08:09 UTC, Siddharth2207 commented
> ok so it seems it wasn't clear that i was rejecting the PR earlier
> 
> please delete the readme so that it doesn't exist to contradict the strats and tests

Removed.

2024-06-07 06:52 UTC, thedavidmeister requested changes

2024-06-07 06:52 UTC, thedavidmeister commented on src/tranche/tranche-space.rain
> +    address: 0xb06202aA3Fe7d85171fB7aA5f17011d17E63f382
is this in all the pubstrats that need it?

2024-08-21 18:01 UTC, closed without merging