Fixed Grid Strategy
rainlanguage/rain.dex.pubstrats pull request #56
Opened 2024-06-13 16:27 UTC by Siddharth2207

## Motivation

This strategy trades mean amount of stable denominated input tokens at the end of every cooldown period provided that current calculated equivalent price of tokens falls within the price gird.

## Checks

By submitting this for review, I'm confirming I've done the following:
- [ ] made this PR as small as possible
- [ ] unit-tested any new functionality
- [ ] linked any relevant issues or PRs

2024-06-15 04:06 UTC, thedavidmeister requested changes

2024-06-15 04:06 UTC, thedavidmeister commented on src/wip/fixed-grid.rain
> +      uniswap-v3-twap-output-ratio(
how is this a grid strat if you're just taking the oracle price for every trade?

why are you using a 0 0 twap instead of an exact quote word?

2024-06-16 09:47 UTC, thedavidmeister requested changes

2024-06-16 09:47 UTC, thedavidmeister commented on src/wip/fixed-trader.rain
> +# provided that current calculated BLUE denominated price of RED falls above a set ratio.
i don't think the defining quality of this strat is that it has a lower bound on the io ratio, that seems to just be a param you can set

2024-06-16 09:47 UTC, thedavidmeister commented on src/wip/fixed-trader.rain
>  # High level, this strategy trades mean amount of BLUE denominated RED tokens at the end of every cooldown period
do we really want to be using a cooldown or would a per second budget work better?

for example, this strat has no DOS protection against someone dusting the cooldown, but a per second budget doesn't have this issue

2024-06-16 09:47 UTC, thedavidmeister commented on src/wip/fixed-trader.rain
> +      uniswap-v3-twap-output-ratio(
why is this different to the prod binding for the same?

2024-06-16 09:47 UTC, thedavidmeister commented on src/wip/fixed-trader.rain
> +        1
why is this 1?

2024-06-16 09:47 UTC, thedavidmeister commented on src/wip/fixed-trader.rain
> +    greater-than-or-equal-to(current-price min-trade-price)
why are we calling things "price" instead of io ratio?

2024-06-16 09:47 UTC, thedavidmeister commented on src/wip/fixed-trader.rain
> +  usd-amount18
don't think we need the 18 convention if it's all decimal math

2024-06-16 09:47 UTC, thedavidmeister commented on src/wip/fixed-trader.rain
> +  jittered-amount-usd18: mul(
what problem does a jittery binomial solve in a DCA strategy?

2024-06-17 11:54 UTC, Siddharth2207 commented
As discussed on the telegram group will have design review for the strategy before putting stuff in pubstrats.

2024-08-21 14:35 UTC, hardyjosh commented
Closing per conversation with @Siddharth2207 in telegram

2024-08-21 14:35 UTC, closed without merging